### ISSUE TITLE
visualthinker doesn't exist?

### ISSUE THREAD

**Issue by WhaleCancer** [inkoalawetrust/KAI#1]
Hey! The last version of this worked for me with no problem, but having this loaded alone or with the Smart-Marines (https://github.com/inkoalawetrust/Smart-Marines). With just KAI (and doom2.wad and gzdoom.pk3) loaded, I get this error:

> Failed to apply MAPINFO DoomEdNum override "1701 = kai_sectorhazard": failed to find corresponding actor class...
> ZSCRIPT error in "KAI.pk3\ZScript\Bases\Projectile.zsc", line 664. Fatal: Class "KAI_Tracer" is trying to inherit from "visualthinker" which does not exist..
> Failed to apply MAPINFO DoomEdNum override "1700 = kai_hazardzone": failed to find corresponding actor class...

Not sure what to do!

**Comment by inkoalawetrust** [comment]
Which version of GZDoom are you using? VisualThinkers were added in 4.12. When I load it in 4.13.2 it loads just fine.

**Comment by WhaleCancer** [comment]
Oof! That was it. I was running an old version of GZDoom. Thanks!

**Comment by inkoalawetrust** [comment]
I'm surprised it didn't give you an error about that, Since the library's ZScript version is set to 4.12.0. Also lol, did you find the notification so quick because it was posted by the webhook on my server?
